<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Session 4 Example: SEO Meta Tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="AI Tools for PHP Developers - A comprehensive training project to boost your productivity using AI.">
    <meta name="keywords" content="PHP, AI, Laravel, ChatGPT, GitHub Copilot, Training">
    <meta name="author" content="PHP Student">
    <title>AI Tools for PHP Developers | Home</title>
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/css/style.css" rel="stylesheet">
</head>
<body>

    <?php include 'navbar.php'; ?>

    <!-- Session 4 Example: Hero Section -->
    <section class="hero-section">
        <div class="container">
            <h1 class="display-4 fw-bold">Supercharge Your PHP Development</h1>
            <p class="lead mt-3">Learn to integrate AI tools like ChatGPT, GitHub Copilot, and OpenAI APIs into your workflow.</p>
            <a href="register.php" class="btn btn-light btn-lg mt-4 px-5 rounded-pill shadow">Get Started Now</a>
        </div>
    </section>

    <div class="container my-5">
        
        <!-- Session 1 Example: Concepts -->
        <div class="row mb-5 text-center">
            <div class="col-12">
                <h2 class="mb-4">Session 1: AI in Web Development</h2>
                <div class="card shadow-sm border-0 bg-white p-4">
                    <h5>AI-Generated vs Human-Written Code</h5>
                    <p class="text-muted mb-0">AI writes code faster but might lack deep context. Humans provide the architecture and security constraints. A hybrid approach (AI-assisted development) is the modern standard.</p>
                </div>
            </div>
        </div>

        <!-- Session 1 Example: Laravel Route Groups Snippet -->
        <div class="row mb-5">
            <div class="col-12">
                <div class="card shadow border-0">
                    <div class="card-header bg-dark text-white">
                        <h5 class="mb-0">Laravel Snippet: Route Groups</h5>
                    </div>
                    <div class="card-body bg-light">
                        <pre class="mb-0"><code>&lt;?php
// routes/web.php
use Illuminate\Support\Facades\Route;

// This is a Laravel route group example generated by AI
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/profile', [ProfileController::class, 'show'])->name('profile');
});
?&gt;</code></pre>
                    </div>
                </div>
            </div>
        </div>

        <!-- Session 4 Example: Product Cards -->
        <div class="row g-4">
            <div class="col-12 text-center mt-5">
                <h2>Session 4: AI for Design & Content</h2>
                <p>AI can help generate beautiful UI components and placeholder content.</p>
            </div>
            
            <div class="col-md-4">
                <div class="card product-card h-100 p-3">
                    <div class="card-body text-center">
                        <h4 class="card-title text-primary">ChatGPT</h4>
                        <p class="card-text">Generate boilerplate code, debug errors, and brainstorm logic instantly.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card product-card h-100 p-3">
                    <div class="card-body text-center">
                        <h4 class="card-title text-success">GitHub Copilot</h4>
                        <p class="card-text">AI pair programmer right inside your VS Code editor.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card product-card h-100 p-3">
                    <div class="card-body text-center">
                        <h4 class="card-title text-info">OpenAI API</h4>
                        <p class="card-text">Integrate intelligent features directly into your PHP and Laravel applications.</p>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="assets/js/script.js"></script>
</body>
</html>
